# Generated by Django 4.1a1 on 2022-05-30 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.ImageField(upload_to="assets/"),
        ),
        migrations.AlterField(
            model_name="department",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_departments",
                to="asset.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asset.department",
            ),
        ),
    ]
