# Generated by Django 4.1a1 on 2022-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_picture_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("M", "Manager"), ("C", "Co-Manager"), ("E", "Employee")],
                default="E",
                max_length=1,
            ),
        ),
    ]
