# Generated by Django 4.1a1 on 2022-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="type",
            field=models.CharField(default="fixrequest", max_length=50),
            preserve_default=False,
        ),
    ]
