# Generated by Django 4.1a1 on 2022-07-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_request_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="type",
        ),
    ]
